### ISSUE TITLE
Feedback on HW1

### ISSUE THREAD

**Issue by sorooshafiee** [ggrrll/tatoule#1]
Hi guys,

First of all, you did a great job in the first homework. Everything was correct and the codes were really clean. Here are my comments:

1- For Exercise 3 (in Intro to Panda ipython file), it is better to print the number of players instead of showing them and inferring their number. My suggestion is to use the simple sum function together with isin. Something like this:
sum(baseball.team.isin(searched_teams))

2- I am glad that you carefully check the excel files in the advanced exercise. Especially, observing both columns "New deaths registered" and "New deaths registered today" are required to be checked in order to find the correct results.

3- I would suggest that all group members stick to python 2 or python 3. The code in the first notebook is based on python 3 while the second notebook require python 3.

4- The version 2 of the first exercise in Data Wrangling with Pandas ipython file contains error. It would be great if you fixed it :)

**Comment by maximepeschard** [comment]
@sorooshafiee Hi !

Thanks a lot for your comments ! 👍 
Just pushed a commit with some fixes. Anyway, we'll definitely take this into account for further homework ! And by the way, sorry about the second notebook pushed in a rush without any output... 😁
